### ISSUE TITLE
Issues running Django Instance

### ISSUE THREAD

**Issue by bryant-huang** [mikeyk/saveourfaves-server#1]
Hey Mikey - thanks so much for working on this, it's an awesome product. I'm a pretty junior developer in university trying to spin off a version of this, not a whole lot of docker experience. I followed all the instructions but when I run `docker ps` it only shows that the postgres container is running. Running `docker ps -a` shows that the two docker containers for frontend and backend have already been exited. Any clue why this happening and not running the Django instance?

**Comment by JSeam2** [comment]
It could be the case that the containers had terminated due to some problems with execution. Could you run `docker logs -t <name of the container>` this way you can see what are the issues that had emerged. If you would like people to help you please provide specifics regarding your environment, steps to reproduce the problem, and relevant logs.

**Comment by mikeyk** [comment]
Hey @bryant-huang, seconding @JSeam2's idea (you can also just do `docker logs -f` to stream the logs as they happen). Feel free to share a [Gist](http://gist.github.com/) of the output if you're seeing any errors in the logs.

**Comment by bryant-huang** [comment]
Hey @mikeyk and @JSeam2, thanks for the input. Using a Windows 10 system with Docker Toolbox - seemed to have the `nginx` and `Django` 'instances running now, but rather the `Postgres` instance giving me some trouble. Have embedded a gist below - there's a fatal error regarding ownership. Looking through web solutions but thought I'd just give more insight.

https://gist.github.com/bryant-huang/ce2ed45c8ed5a0ddfc436989e2d5e6ef

**Comment by JSeam2** [comment]
@bryant-huang
Noting these errors 
```
2020-03-23 18:21:29.906 UTC [80] FATAL:  data directory "/var/lib/postgresql/data" has wrong ownership
2020-03-23 18:21:29.906 UTC [80] HINT:  The server must be started by the user that owns the data directory.
```

This might be a result of the following line in `db/docker-compose.yml`. 
```
volumes:
        - ./postgres-data:/var/lib/postgresql/data/
```
Check what kind of virtualization you are using atm, it might be a Windows 10 filesystem permissioning issue. What is happening is that the docker instances are trying to read/write into the particular local directory but is not given access. If you are using something like virtualbox you might need to configure folder permissions in virtualbox. A possibility is to simply omit the `volumes` section in the `db/docker-compose.yml` and avoid the reference to your window filesystem.

**Comment by bryant-huang** [comment]
Hey, just got the chance to look at this again. Every instance is up and running properly thank you all for your help!
